### ISSUE TITLE
crash on iOS

### ISSUE THREAD

**Issue by TomTasche** [andiwand/OpenDocument.core#20]
the app crashed with the following stacktrace on ios. is that enough to get an idea what went wrong?

> Crashed: com.apple.main-thread
> 0  OpenDocumentReader             0x102f2fcec odr::CryptoUtil::base64Encode(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 166592
> 1  OpenDocumentReader             0x102f2f8c4 odr::ImageTranslator::translateStart(tinyxml2::XMLElement const&, std::__1::basic_ostream<char, std::__1::char_traits<char> >&, odr::Context&) const + 165528
> 2  OpenDocumentReader             0x102f2bddc odr::DefaultContentTranslatorImpl::translate(tinyxml2::XMLElement const&, odr::Context&) const + 150448
> 3  OpenDocumentReader             0x102f2be68 odr::DefaultContentTranslatorImpl::translate(tinyxml2::XMLElement const&, odr::Context&) const + 150588
> 4  OpenDocumentReader             0x102f2be68 odr::DefaultContentTranslatorImpl::translate(tinyxml2::XMLElement const&, odr::Context&) const + 150588
> 5  OpenDocumentReader             0x102f2be68 odr::DefaultContentTranslatorImpl::translate(tinyxml2::XMLElement const&, odr::Context&) const + 150588
> 6  OpenDocumentReader             0x102f2be68 odr::DefaultContentTranslatorImpl::translate(tinyxml2::XMLElement const&, odr::Context&) const + 150588
> 7  OpenDocumentReader             0x102f2be68 odr::DefaultContentTranslatorImpl::translate(tinyxml2::XMLElement const&, odr::Context&) const + 150588
> 8  OpenDocumentReader             0x102f2be68 odr::DefaultContentTranslatorImpl::translate(tinyxml2::XMLElement const&, odr::Context&) const + 150588
> 9  OpenDocumentReader             0x102f343a4 odr::DefaultDocumentTranslatorImpl::translate(odr::OpenDocumentFile&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, odr::Context&) const + 184696
> 10 OpenDocumentReader             0x102f42064 odr::TranslationHelperImpl::translate(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, odr::TranslationConfig const&) const + 241208

EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000017

**Comment by TomTasche** [comment]
if it's not enough information, please close the ticket until we have a document that produces this error @andiwand

**Comment by andiwand** [comment]
@TomTasche do you know if it is the very recent version with the "path normalization fix" (7b000f9)? if so it could be the same bug as #19
if it's the newest version i still think it is the same problem but with another path normalization issue i don't catch. for now i will check if the file exists and if not write an error to the log.

**Comment by andiwand** [comment]
this commit will fix the crash but the image will not be displayed

**Comment by TomTasche** [comment]
Thanks! Yes, it was the latest version. Fix looks good for now!
