### ISSUE TITLE
More robust editing

### ISSUE THREAD

**Issue by TomTasche** [andiwand/OpenDocument.core#54]
Backtranslate currently fails if the HTML does not match the expected structure. For example, iOS adds "colgroup"-tags to the translated HTML, making backtranslation fail.

**Comment by andiwand** [comment]
starting point https://github.com/andiwand/OpenDocument.core/tree/feature/robust-editing

**Comment by andiwand** [comment]
1ffb3ba87e3a6c9f4a6dae129728fd5cbf634150
