### ISSUE TITLE
Support modification of multi-sheet files

### ISSUE THREAD

**Issue by TomTasche** [andiwand/OpenDocument.core#63]
Editing one sheet of a file and switching between sheets before saving might break backtranslation due to entryOffset.

**Comment by TomTasche** [comment]
https://github.com/andiwand/OpenDocument.core/blob/afa78c9344ea2dc402d7b82bcee699845c25af9f/src/odf/OpenDocumentTranslator.cpp#L114

**Comment by andiwand** [comment]
back translation wont work for spreadsheet and presentation right now.
- ods/odp have one content xml and can result in multiple html files with ambiguous editing ids. the diff json would have to be merged or referenced to its sheet.
- pptx/xlsx have multiple content files and can result in multiple html files. this is not handled at all right now.

**Comment by andiwand** [comment]
@TomTasche do you think this issue is gone?

**Comment by TomTasche** [comment]
As you said, the issue is still there but we have identified a workaround. Linking to https://github.com/andiwand/OpenDocument.core/issues/123 and closing
